### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by kozi**
Changed jquery dependency from **"~1.8"** to **">=1.8"**.

### CODE REVIEW

**Comment by kozi** [comment]
To enable this change you have to release a new version because the bower package manager only checks the versions you released and in the current version *1.7.5* the "old" bower.json with *jquery ~1.8* is used.

**Comment by tomsommer** [comment]
Please tag a new release!

**Comment by joeldbirch** [comment]
Okay, definitely next week.

**Comment by joeldbirch** [comment]
This has been done. I also published it as an NPM package. Thanks for the prompts.

**Pull request merged**
